services:
  bot:
    build: .
    network_mode: host
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - MONGODB_URI=${MONGODB_URI}
      - OLAF_CHANNEL_ID=${OLAF_CHANNEL_ID}
      - MAIN_CHANNEL_ID=${MAIN_CHANNEL_ID}
      - MAIN_CHANNEL_USERNAME=${MAIN_CHANNEL_USERNAME}
      - CRON_JOB_TIME=${CRON_JOB_TIME}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - SERVER_BASE_URL=${SERVER_BASE_URL}
      - WEEKLY_CRON_JOB_TIME=${WEEKLY_CRON_JOB_TIME}
    ports:
      - "8080:${SERVER_PORT}"
    restart: unless-stopped
