// Seed data for the personality catalog: trait registry, tests and questions.
// Applied by src/personality/migrate.js (idempotent, versioned). Tuning a trait's
// learning_rate / stability / enabled flag in the DB survives re-runs unless the
// seed's `version` is bumped.

// Category defaults: Big Five is slow-changing, communication style adapts fast.
//   stability     = how far a trait may drift from its baseline (1 - stability)
//   learning_rate = share of an observation blended in per update (× confidence)
const CATEGORY_DEFAULTS = {
  big_five:            { stability: 0.9,  learning_rate: 0.03 },
  big_five_facet:      { stability: 0.85, learning_rate: 0.04 },
  communication:       { stability: 0.3,  learning_rate: 0.2 },
  emotional_style:     { stability: 0.5,  learning_rate: 0.12 },
  thinking_style:      { stability: 0.6,  learning_rate: 0.1 },
  behavioral:          { stability: 0.6,  learning_rate: 0.1 },
};

const CATEGORY_NAMES = {
  big_five: 'Big Five',
  big_five_facet: 'Big Five facets',
  communication: 'Communication preferences',
  emotional_style: 'Conversation & emotional style',
  thinking_style: 'Thinking & decision style',
  behavioral: 'Behavioral preferences',
};

// [key, name, description]
const TRAIT_ROWS = {
  big_five: [
    ['openness', 'Openness', 'Curiosity, imagination and openness to new ideas and experiences.'],
    ['conscientiousness', 'Conscientiousness', 'Organisation, dependability and self-discipline.'],
    ['extraversion', 'Extraversion', 'Sociability, energy and enjoyment of being around people.'],
    ['agreeableness', 'Agreeableness', 'Compassion, cooperativeness and trust in others.'],
    ['neuroticism', 'Neuroticism', 'Tendency to experience negative emotions such as anxiety or moodiness.'],
  ],
  big_five_facet: [
    ['imagination', 'Imagination', 'Rich fantasy life and vivid mental imagery.'],
    ['artistic_interest', 'Artistic interest', 'Appreciation of art, beauty and aesthetics.'],
    ['emotionality', 'Emotionality', 'Awareness of and openness to one\'s own feelings.'],
    ['adventurousness', 'Adventurousness', 'Eagerness to try new activities and experiences.'],
    ['intellect', 'Intellect', 'Interest in abstract ideas and intellectual challenges.'],
    ['self_efficacy', 'Self-efficacy', 'Confidence in one\'s ability to accomplish things.'],
    ['orderliness', 'Orderliness', 'Preference for structure, tidiness and organisation.'],
    ['achievement_striving', 'Achievement striving', 'Drive to set and reach ambitious goals.'],
    ['self_discipline', 'Self-discipline', 'Ability to start and finish tasks despite distractions.'],
    ['friendliness', 'Friendliness', 'Warmth and ease in making friends.'],
    ['gregariousness', 'Gregariousness', 'Enjoyment of crowds and group company.'],
    ['assertiveness', 'Assertiveness', 'Taking charge and speaking up.'],
    ['activity_level', 'Activity level', 'Pace of life and preference for being busy.'],
    ['excitement_seeking', 'Excitement seeking', 'Craving stimulation and thrills.'],
    ['cheerfulness', 'Cheerfulness', 'Tendency to feel joy and optimism.'],
    ['trust', 'Trust', 'Belief that others are honest and well-intentioned.'],
    ['altruism', 'Altruism', 'Genuine concern for and willingness to help others.'],
    ['cooperation', 'Cooperation', 'Preference for compromise over confrontation.'],
    ['modesty', 'Modesty', 'Reluctance to claim superiority over others.'],
    ['sympathy', 'Sympathy', 'Tender-heartedness and compassion.'],
    ['anxiety', 'Anxiety', 'Tendency to worry and feel tense.'],
    ['anger', 'Anger', 'How easily frustration turns into irritation or anger.'],
    ['depression', 'Depression', 'Tendency towards low mood and discouragement.'],
    ['self_consciousness', 'Self-consciousness', 'Sensitivity to what others think; shyness.'],
    ['vulnerability', 'Vulnerability', 'Difficulty coping under stress or pressure.'],
  ],
  communication: [
    ['communication_directness', 'Directness', 'Preference for blunt, straight-to-the-point communication over softened phrasing.'],
    ['communication_formality', 'Formality', 'Preference for formal language over casual, relaxed tone.'],
    ['preferred_response_length', 'Response length', 'Preference for detailed, long answers (high) versus concise ones (low).'],
    ['technical_depth', 'Technical depth', 'Desire for technical, in-depth explanations.'],
    ['explanation_detail', 'Explanation detail', 'Desire for step-by-step, thorough explanations.'],
    ['preference_for_examples', 'Examples', 'How much the user values concrete examples.'],
    ['preference_for_summaries', 'Summaries', 'How much the user values TL;DR style summaries.'],
  ],
  emotional_style: [
    ['emotional_expressiveness', 'Emotional expressiveness', 'How openly the user shares feelings in conversation.'],
    ['emotional_support_preference', 'Emotional support preference', 'Preference for empathy and validation over pure problem-solving.'],
    ['humor_preference', 'Humor', 'Appreciation of jokes and playful tone.'],
    ['seriousness', 'Seriousness', 'Preference for a serious, focused tone.'],
    ['enthusiasm', 'Enthusiasm', 'Energy and excitement expressed in conversation.'],
    ['warmth', 'Warmth', 'Preference for a friendly, caring tone.'],
  ],
  thinking_style: [
    ['analytical_thinking', 'Analytical thinking', 'Reliance on logic, data and structured reasoning.'],
    ['intuitive_thinking', 'Intuitive thinking', 'Reliance on gut feeling and pattern recognition.'],
    ['decision_speed', 'Decision speed', 'Tendency to decide quickly rather than slowly.'],
    ['deliberation', 'Deliberation', 'Tendency to weigh options carefully before acting.'],
    ['need_for_certainty', 'Need for certainty', 'Discomfort with open questions and unknowns.'],
    ['ambiguity_tolerance', 'Ambiguity tolerance', 'Comfort with vague or unresolved situations.'],
  ],
  behavioral: [
    ['risk_tolerance', 'Risk tolerance', 'Willingness to accept uncertain outcomes.'],
    ['novelty_seeking', 'Novelty seeking', 'Attraction to new things and change.'],
    ['patience', 'Patience', 'Ability to wait calmly.'],
    ['persistence', 'Persistence', 'Continuing despite setbacks.'],
    ['flexibility', 'Flexibility', 'Willingness to change plans and adapt.'],
    ['routine_preference', 'Routine preference', 'Comfort in predictable, repeated patterns.'],
    ['goal_orientation', 'Goal orientation', 'Focus on outcomes and targets.'],
    ['curiosity', 'Curiosity', 'Desire to explore and learn.'],
  ],
};

const TRAITS = Object.entries(TRAIT_ROWS).flatMap(([category, rows]) =>
  rows.map(([key, name, description]) => ({
    key,
    name,
    category,
    description,
    default_value: 0.5,
    min_value: 0,
    max_value: 1,
    stability: CATEGORY_DEFAULTS[category].stability,
    learning_rate: CATEGORY_DEFAULTS[category].learning_rate,
    enabled: true,
    version: 1,
  }))
);

// ---- Tests ----
// Every test uses the same 5-point scale and likert_mean scoring; each item maps to one
// trait key from the catalog above, `reverse` flips it. Add a test by appending here
// (or by inserting documents into personality_tests / personality_test_questions).

const LIKERT_5 = {
  min: 1,
  max: 5,
  labels: ['Very inaccurate', 'Somewhat inaccurate', 'Neutral', 'Somewhat accurate', 'Very accurate'],
};

const INTRO = 'For each statement, pick how accurately it describes you. There are no right or wrong answers, so go with your first instinct.';

// items: [trait, text, reverse]
const TEST_DEFINITIONS = [
  {
    key: 'big_five',
    order: 10,
    name: 'Big Five personality test',
    description: 'The five major personality dimensions. A good place to start.',
    // Mini-IPIP (Donnellan et al., 2006), public domain
    scoring: { method: 'likert_mean', confidence: 0.7 },
    items: [
      ['extraversion', 'I am the life of the party.', false],
      ['agreeableness', 'I sympathize with others\' feelings.', false],
      ['conscientiousness', 'I get chores done right away.', false],
      ['neuroticism', 'I have frequent mood swings.', false],
      ['openness', 'I have a vivid imagination.', false],
      ['extraversion', 'I don\'t talk a lot.', true],
      ['agreeableness', 'I am not interested in other people\'s problems.', true],
      ['conscientiousness', 'I often forget to put things back in their proper place.', true],
      ['neuroticism', 'I am relaxed most of the time.', true],
      ['openness', 'I am not interested in abstract ideas.', true],
      ['extraversion', 'I talk to a lot of different people at parties.', false],
      ['agreeableness', 'I feel others\' emotions.', false],
      ['conscientiousness', 'I like order.', false],
      ['neuroticism', 'I get upset easily.', false],
      ['openness', 'I have difficulty understanding abstract ideas.', true],
      ['extraversion', 'I keep in the background.', true],
      ['agreeableness', 'I am not really interested in others.', true],
      ['conscientiousness', 'I make a mess of things.', true],
      ['neuroticism', 'I seldom feel blue.', true],
      ['openness', 'I do not have a good imagination.', true],
    ],
  },
  {
    key: 'communication_style',
    order: 20,
    name: 'Communication style',
    description: 'How you like information delivered: directness, tone, length, depth, examples.',
    scoring: { method: 'likert_mean', confidence: 0.6 },
    items: [
      ['communication_directness', 'I prefer people to tell me things straight, even if it is blunt.', false],
      ['communication_formality', 'I prefer a polite, formal tone in conversations.', false],
      ['preferred_response_length', 'I like thorough answers that cover every detail.', false],
      ['technical_depth', 'I want to know how things work under the hood.', false],
      ['explanation_detail', 'I like step-by-step explanations.', false],
      ['preference_for_examples', 'A good example helps me more than a definition.', false],
      ['preference_for_summaries', 'I appreciate a quick summary before the details.', false],
      ['communication_directness', 'I would rather someone soften bad news than say it plainly.', true],
      ['communication_formality', 'I like conversations to be casual and relaxed.', true],
      ['preferred_response_length', 'I prefer short answers. Just give me the gist.', true],
      ['technical_depth', 'Technical details usually bore me.', true],
      ['explanation_detail', 'I get impatient with long explanations.', true],
      ['preference_for_examples', 'I do not need examples to understand an idea.', true],
      ['preference_for_summaries', 'Summaries feel unnecessary to me. I would rather read everything.', true],
    ],
  },
  {
    key: 'thinking_style',
    order: 30,
    name: 'Thinking & decision style',
    description: 'Analytical vs. intuitive, fast vs. deliberate, and how you handle uncertainty.',
    scoring: { method: 'likert_mean', confidence: 0.6 },
    items: [
      ['analytical_thinking', 'I like to break problems down and weigh the facts.', false],
      ['intuitive_thinking', 'I trust my gut feeling when making choices.', false],
      ['decision_speed', 'I make decisions quickly.', false],
      ['deliberation', 'I think through the consequences before I act.', false],
      ['need_for_certainty', 'I feel uneasy until I know exactly how things will turn out.', false],
      ['ambiguity_tolerance', 'I am comfortable with vague or open-ended situations.', false],
      ['analytical_thinking', 'I rarely analyze things in detail before acting.', true],
      ['intuitive_thinking', 'I distrust hunches that are not backed by evidence.', true],
      ['decision_speed', 'I take a long time to make up my mind.', true],
      ['deliberation', 'I often act first and think later.', true],
      ['need_for_certainty', 'I am fine not knowing how things will end up.', true],
      ['ambiguity_tolerance', 'Unclear instructions frustrate me.', true],
    ],
  },
  {
    key: 'emotional_style',
    order: 40,
    name: 'Conversation & emotional style',
    description: 'How expressive you are and the tone you enjoy: humor, warmth, support, seriousness.',
    scoring: { method: 'likert_mean', confidence: 0.6 },
    items: [
      ['emotional_expressiveness', 'I openly share how I feel.', false],
      ['emotional_support_preference', 'When I have a problem, I want understanding before solutions.', false],
      ['humor_preference', 'I love it when conversations are playful and funny.', false],
      ['seriousness', 'I prefer to keep conversations focused and serious.', false],
      ['enthusiasm', 'I get excited easily and show it.', false],
      ['warmth', 'I like a warm, friendly tone in conversations.', false],
      ['emotional_expressiveness', 'I keep my feelings to myself.', true],
      ['emotional_support_preference', 'When I have a problem, just help me fix it. I do not need sympathy.', true],
      ['humor_preference', 'Jokes in a serious conversation annoy me.', true],
      ['seriousness', 'I find overly serious conversations tiring.', true],
      ['enthusiasm', 'I rarely show much excitement.', true],
      ['warmth', 'I prefer people to be neutral and businesslike with me.', true],
    ],
  },
  {
    key: 'behavioral_preferences',
    order: 50,
    name: 'Behavioral preferences',
    description: 'Risk, novelty, patience, persistence, flexibility, routine, goals and curiosity.',
    scoring: { method: 'likert_mean', confidence: 0.6 },
    items: [
      ['risk_tolerance', 'I am willing to take risks for a big reward.', false],
      ['novelty_seeking', 'I love trying new things.', false],
      ['patience', 'I can wait calmly when things take time.', false],
      ['persistence', 'I keep going even when things get hard.', false],
      ['flexibility', 'I adapt easily when plans change.', false],
      ['routine_preference', 'I like having a regular routine.', false],
      ['goal_orientation', 'I set clear goals and work toward them.', false],
      ['curiosity', 'I am always curious to learn how things work.', false],
      ['risk_tolerance', 'I avoid situations with uncertain outcomes.', true],
      ['novelty_seeking', 'I prefer the familiar over the new.', true],
      ['patience', 'I get frustrated when I have to wait.', true],
      ['persistence', 'I give up easily when I hit obstacles.', true],
      ['flexibility', 'Changes to my plans throw me off.', true],
      ['routine_preference', 'A fixed routine makes me feel trapped.', true],
      ['goal_orientation', 'I rarely set specific goals.', true],
      ['curiosity', 'I seldom feel curious about new topics.', true],
    ],
  },
  {
    key: 'big_five_facets',
    order: 60,
    name: 'Big Five facets (in depth)',
    description: 'A longer test covering the 25 facets behind the Big Five. Best taken after the Big Five test.',
    scoring: { method: 'likert_mean', confidence: 0.6 },
    items: [
      ['imagination', 'I enjoy daydreaming and letting my mind wander.', false],
      ['artistic_interest', 'I am moved by art, music or beauty.', false],
      ['emotionality', 'I am aware of my feelings as they happen.', false],
      ['adventurousness', 'I like to visit new places and try new activities.', false],
      ['intellect', 'I enjoy thinking about abstract ideas.', false],
      ['self_efficacy', 'I complete tasks successfully.', false],
      ['orderliness', 'I like to keep things tidy and in order.', false],
      ['achievement_striving', 'I work hard to reach my goals.', false],
      ['self_discipline', 'I start tasks right away and finish them.', false],
      ['friendliness', 'I make friends easily.', false],
      ['gregariousness', 'I love large parties and crowds.', false],
      ['assertiveness', 'I take charge in groups.', false],
      ['activity_level', 'I am always busy and on the go.', false],
      ['excitement_seeking', 'I seek out thrills and adventure.', false],
      ['cheerfulness', 'I feel happy and cheerful most days.', false],
      ['trust', 'I believe most people have good intentions.', false],
      ['altruism', 'I enjoy helping others.', false],
      ['cooperation', 'I would rather compromise than fight.', false],
      ['modesty', 'I dislike being the center of attention.', false],
      ['sympathy', 'I feel for people who are less fortunate.', false],
      ['anxiety', 'I worry about things.', false],
      ['anger', 'I get irritated easily.', false],
      ['depression', 'I often feel down or blue.', false],
      ['self_consciousness', 'I am easily embarrassed.', false],
      ['vulnerability', 'I feel overwhelmed when things go wrong.', false],
      ['imagination', 'I seldom get lost in my thoughts.', true],
      ['artistic_interest', 'I do not care much for art.', true],
      ['emotionality', 'I rarely notice my emotional reactions.', true],
      ['adventurousness', 'I prefer to stick with what I know.', true],
      ['intellect', 'I avoid philosophical discussions.', true],
      ['self_efficacy', 'I doubt my ability to handle things.', true],
      ['orderliness', 'I leave my things lying around.', true],
      ['achievement_striving', 'I do just enough to get by.', true],
      ['self_discipline', 'I have trouble making myself get started.', true],
      ['friendliness', 'I am hard to get to know.', true],
      ['gregariousness', 'I prefer to be alone.', true],
      ['assertiveness', 'I wait for others to lead the way.', true],
      ['activity_level', 'I like to take it easy.', true],
      ['excitement_seeking', 'I dislike loud, wild situations.', true],
      ['cheerfulness', 'I am seldom in a lighthearted mood.', true],
      ['trust', 'I am suspicious of other people\'s motives.', true],
      ['altruism', 'I look out for myself first.', true],
      ['cooperation', 'I enjoy a good argument.', true],
      ['modesty', 'I think I am better than most people.', true],
      ['sympathy', 'I am not affected by other people\'s misfortune.', true],
      ['anxiety', 'I rarely feel tense or nervous.', true],
      ['anger', 'I rarely get mad.', true],
      ['depression', 'I feel comfortable with myself.', true],
      ['self_consciousness', 'I am not bothered by what people think of me.', true],
      ['vulnerability', 'I stay calm under pressure.', true],
    ],
  },
];

const TESTS = TEST_DEFINITIONS.map(({ items, ...test }) => ({
  ...test,
  intro: test.intro || INTRO,
  scale: test.scale || LIKERT_5,
  enabled: true,
  version: 1,
}));

const QUESTIONS = TEST_DEFINITIONS.flatMap(test =>
  test.items.map(([trait, text, reverse], i) => ({
    test_key: test.key,
    order: i + 1,
    text,
    trait,
    reverse,
    enabled: true,
    version: 1,
  }))
);

module.exports = {
  CATEGORY_DEFAULTS,
  CATEGORY_NAMES,
  TRAITS,
  TESTS,
  QUESTIONS,
};
