// Builds src/public/lib/vendor/icons.js: the Lucide (https://lucide.dev, ISC) icons the mini app uses,
// and only those, so the page doesn't download the whole set. Add a name below, then run `yarn icons`.
// The page draws them with <ui-icon name="users">.
const fs = require('fs');
const path = require('path');
const lucide = require('lucide');

const NAMES = [
  // tab bar
  'users', 'brain', 'scroll-text', 'shield', 'settings',
  // admin
  'waypoints', 'alarm-clock', 'megaphone', 'hard-drive-download', 'sliders-horizontal', 'arrow-up-down',
  'activity', 'calendar-plus', 'arrow-down-a-z', 'notebook-pen', 'user-check', 'ban', 'shield-check',
  'search', 'search-x', 'rotate-ccw', 'drama',
  // states and buttons
  'wifi-off', 'triangle-alert', 'user-plus', 'user-x', 'user', 'lock', 'lock-keyhole', 'link', 'smile-plus',
  'circle-check', 'clipboard-list', 'send', 'eraser', 'plug', 'save', 'heart-pulse', 'package', 'folder-open',
  'upload', 'download', 'globe', 'map-pin', 'bot', 'x', 'message-circle', 'eye-off', 'heart-crack', 'check',
  'undo-2', 'refresh-cw', 'arrow-left-right', 'info', 'party-popper', 'chevron-down', 'notepad-text-dashed',
  // admin characteristics
  'sparkles', 'chart-column', 'arrow-down-wide-narrow', 'arrow-up-narrow-wide', 'message-circle-heart', 'history', 'quote', 'thumbs-down', 'target', 'heart-handshake', 'lightbulb', 'zap', 'flame',
  // OpenAI key filter
  'key-round', 'circle-off',
  'compass', 'users-round', 'calendar-check', 'waves', 'anchor', 'thumbs-up', 'messages-square', 'book-open', 'telescope', 'sun', 'handshake',
];

const pascal = (name) => name.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const icons = {};
for (const name of NAMES) {
  const node = lucide[pascal(name)];
  if (!node) throw new Error(`No Lucide icon named "${name}"`);
  icons[name] = node;
}

const version = require('lucide/package.json').version;
const out = `/*! Lucide icons v${version} (subset) | ISC License | Copyright (c) Lucide Icons and Contributors | https://lucide.dev */
/* generated by scripts/build-icons.js; do not edit by hand */
window.MP_ICONS = ${JSON.stringify(icons)};
`;
const file = path.join(__dirname, '..', 'src', 'public', 'lib', 'vendor', 'icons.js');
fs.writeFileSync(file, out);
console.log(`${NAMES.length} icons -> ${path.relative(process.cwd(), file)} (${(out.length / 1024).toFixed(1)} KB)`);
